name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow only on push to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The environment in which the job will run
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out the code from the repository
    
    - name: Set up Node.js (if using a build system like React, Angular, etc.)
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version (if applicable)

    - name: Install dependencies (if applicable)
      run: |
        npm install  # This assumes you're using npm to install dependencies

    - name: Build project (if applicable)
      run: |
        npm run build  # Modify this according to your build script (e.g., `npm run build`, `gatsby build`, etc.)

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # The branch you want to deploy to
        folder: dist  # The folder where your build output lives (e.g., `dist`, `build`, `docs`, etc.)
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides this automatically for authentication
